site_name: "ODK-AI"
site_description: Documentation for the ODK-AI container for ontology development with AI tools
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.snippets

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Interactive Mode: interactive-mode.md
  - Headless Mode: headless-mode.md
  - Configuration: configuration.md
  - Building: building.md
  - Roadmap: roadmap.md

site_url: https://cmungall.github.io/odk-ai/
repo_url: https://github.com/cmungall/odk-ai/
